### ISSUE TITLE
Wrong tag for latest image

### ISSUE THREAD

**Issue by cilindrox** [aptible/docker-nodejs#11]
Looks like the latest got published under the `v4.2.x` instead of `v4.3.x`
Using 

```
FROM quay.io/aptible/nodejs:v4.3.x
```

Nets you a `Tag v4.3.x not found in repository quay.io/aptible/nodejs` error

**Comment by fancyremarker** [comment]
@cilindrox : Fixed in #12 and released.

**Comment by cilindrox** [comment]
Awesomesauce, thanks!
