### ISSUE TITLE
Security update

### ISSUE THREAD

**Issue by mshick** [aptible/docker-nodejs#26]
You probably saw there is a critical security update for the Node 6.x line. https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/

Are there plans to update the image?

**Comment by fancyremarker** [comment]
Hi @mshick, thanks for opening this ticket. We will soon be updating our Quickstart guides to reference the library base images (i.e., `FROM node...`), but in the meantime we've upgraded all tags in #27. The latest versions are up for download on Quay.
